[Personal]
from          = Cristobal Riaga <cristobalriaga@gmail.com>
source        = imaps://cristobalriaga%40gmail.com:pfkx%20itzr%20fzle%20wzin@imap.gmail.com
outgoing      = smtps://cristobalriaga%40gmail.com:pfkx%20itzr%20fzle%20wzin@smtp.gmail.com
default       = INBOX
folders-sort  = INBOX
postpone      = [Gmail]/Drafts
cache-headers = true
