kitty_mod ctrl+shift

# Windows
map kitty_mod+n launch --cwd=current 
# NOTE: my external keyboard doesn't seem to detect ctrl+shift+enter
map kitty_mod+enter launch 

map kitty_mod+d close_window

# Tabs
map kitty_mod+f next_tab
map kitty_mod+b previous_tab

# Scrolling
map ctrl+y scroll_line_up
map ctrl+e scroll_line_down
map ctrl+u scroll_page_up
map ctrl+d scroll_page_down

# Clipboard
map ctrl+v paste_from_clipboard
map ctrl+x copy_to_clipboard

map --when-focus-on var:IS_NVIM ctrl+v
map --when-focus-on var:IS_NVIM ctrl+x

# smart-splits.nvim
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# aerc
map --when-focus-on title:aerc ctrl+j
map --when-focus-on title:aerc ctrl+k
map --when-focus-on title:aerc ctrl+h
map --when-focus-on title:aerc ctrl+l

# spotify_player
map --when-focus-on title:spotify_player ctrl+j
map --when-focus-on title:spotify_player ctrl+k
map --when-focus-on title:spotify_player ctrl+h
map --when-focus-on title:spotify_player ctrl+l

# Resizing
# Just use ctrl+shift+r
# the 3 here is the resize amount, adjust as needed
# map kitty_mod+j kitten relative_resize.py down  2
# map kitty_mod+k kitten relative_resize.py up    2
# map kitty_mod+h kitten relative_resize.py left  2
# map kitty_mod+l kitten relative_resize.py right 2

# map --when-focus-on var:IS_NVIM kitty_mod+j
# map --when-focus-on var:IS_NVIM kitty_mod+k
# map --when-focus-on var:IS_NVIM kitty_mod+h
# map --when-focus-on var:IS_NVIM kitty_mod+l
