# https://sw.kovidgoyal.net/kitty/mapping/
# https://sw.kovidgoyal.net/kitty/actions/
kitty_mod ctrl+shift

# Windows
map kitty_mod+n launch --cwd=current 
# NOTE: my external keyboard doesn't seem to detect ctrl+shift+enter
map kitty_mod+enter launch 

map kitty_mod+d close_window

map kitty_mod+q detach_window ask

map ctrl+shift+y next_layout

map --new-mode mw kitty_mod+w

# Move the active window in the indicated direction
map --mode mw ctrl+k move_window up
map --mode mw ctrl+h move_window left
map --mode mw ctrl+l move_window right
map --mode mw ctrl+j move_window down

# Resize the active window
# https://sw.kovidgoyal.net/kitty/layouts/#window-resizing
map --mode mw h resize_window narrower
map --mode mw l resize_window wider
map --mode mw k resize_window taller
map --mode mw j resize_window shorter
map --mode mw shift+h resize_window narrower 3
map --mode mw shift+l resize_window wider 3
map --mode mw shift+k resize_window taller 3
map --mode mw shift+j resize_window shorter 3
map --mode mw = resize_window reset

# Exit the manage window mode
map --mode mw esc pop_keyboard_mode

# Scrollling

map ctrl+u remote_control scroll-window 0.5p-
map ctrl+d remote_control scroll-window 0.5p

map --new-mode scroll kitty_mod+z # Scroll mode

map --mode scroll y scroll_line_up
map --mode scroll e scroll_line_down
map --mode scroll u remote_control scroll-window 0.5p-
map --mode scroll d remote_control scroll-window 0.5p
map --mode scroll b scroll_page_up
map --mode scroll f scroll_page_down
map --mode scroll g scroll_home
map --mode scroll shift+g scroll_end
map --mode scroll k scroll_to_prompt -1
map --mode scroll j scroll_to_prompt 1

map --mode scroll esc pop_keyboard_mode

# Tabs
map kitty_mod+t new_tab
map ctrl+tab
map ctrl+shift+tab

map kitty_mod+h previous_tab
map kitty_mod+l next_tab

# Clipboard
map ctrl+v paste_from_clipboard
map ctrl+x copy_to_clipboard
map ctrl+shift+c copy_to_clipboard


# smart-splits.nvim
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# nvim
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+l

map --when-focus-on var:IS_NVIM ctrl+u
map --when-focus-on var:IS_NVIM ctrl+d

map --when-focus-on var:IS_NVIM ctrl+v
map --when-focus-on var:IS_NVIM ctrl+x

# aerc
map --when-focus-on title:aerc ctrl+j
map --when-focus-on title:aerc ctrl+k
map --when-focus-on title:aerc ctrl+h
map --when-focus-on title:aerc ctrl+l

# spotify_player
map --when-focus-on title:spotify_player ctrl+j
map --when-focus-on title:spotify_player ctrl+k
map --when-focus-on title:spotify_player ctrl+h
map --when-focus-on title:spotify_player ctrl+l

# yazi
map --when-focus-on title:yazi ctrl+u
map --when-focus-on title:yazi ctrl+d
map --when-focus-on title:yazi ctrl+b
map --when-focus-on title:yazi ctrl+f
map --when-focus-on title:yazi ctrl+n
map --when-focus-on title:yazi ctrl+k
map --when-focus-on title:yazi ctrl+p
map --when-focus-on title:yazi ctrl+e
map --when-focus-on title:yazi ctrl+y
map --when-focus-on title:yazi ctrl+a
map --when-focus-on title:yazi ctrl+s
map --when-focus-on title:yazi ctrl+d
map --when-focus-on title:yazi ctrl+w
map --when-focus-on title:yazi ctrl+r

# clipse
map --when-focus-on title:clipse ctrl+u
map --when-focus-on title:clipse ctrl+d

map --when-focus-on title:hours ctrl+x
