include ./theme.conf

allow_remote_control yes
listen_on unix:@mykitty
enabled_layouts fat:bias=80, tall:bias=65
#, horizontal, vertical

# Since my keyboard doesn't seem to detect ctrl+shift+enter
map ctrl+alt+enter launch --cwd=current

# https://github.com/mrjones2014/smart-splits.nvim?tab=readme-ov-file#kitty
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right

# Unset the mapping to pass the keys to neovim
map --when-focus-on var:IS_NVIM ctrl+j
map --when-focus-on var:IS_NVIM ctrl+k
map --when-focus-on var:IS_NVIM ctrl+h
map --when-focus-on var:IS_NVIM ctrl+l

# the 3 here is the resize amount, adjust as needed
map ctrl+shift+j kitten relative_resize.py down  2
map ctrl+shift+k kitten relative_resize.py up    2
map ctrl+shift+h kitten relative_resize.py left  2
map ctrl+shift+l kitten relative_resize.py right 2

map --when-focus-on var:IS_NVIM ctrl+shift+j
map --when-focus-on var:IS_NVIM ctrl+shift+k
map --when-focus-on var:IS_NVIM ctrl+shift+h
map --when-focus-on var:IS_NVIM ctrl+shift+l

map ctrl+y scroll_line_up
map ctrl+e scroll_line_down
map ctrl+u scroll_page_up
map ctrl+d scroll_page_down

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
