tab_bar_edge bottom
tab_bar_margin_height 0 0 
tab_bar_style slant
tab_bar_align center
tab_title_max_length 37

# tab_title_template " ⌘{index} {title[title.rfind('/')+1:]}"
# active_tab_title_template " ⌘{index} {title[title.rfind('/')+1:]}"

tab_title_template          "{bell_symbol or activity_symbol}{title}"
active_tab_title_template   "{' ' if layout_name == 'stack' else ''}{bell_symbol}{title}"

active_tab_font_style bold
inactive_tab_font_style bold

tab_bar_background #78a9ff

inactive_tab_background #78a9ff
inactive_tab_foreground #161616

active_tab_background #161616
active_tab_foreground #f2f4f8
