-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/core/common.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.common")

-- Autostart dunst (notificiation daemon, manages system notifications)

-- Updates the list of environment variables

-- Inhibit shutdown when pressing the power off key, instead run wlogout
hl.on("hyprland.shutdown", function()
	hl.exec_cmd('kill -9 "$(cat /tmp/.hyprland-systemd-inhibit)')
end)

-- Bluetooth

-- Clipboard manager

-- Gamma/temperature filter

-- Watch events for various utilities

-- exec-once = hyprpm reload # Load enabled plugins

-- To fix waybar not showing system tray after using kde apps
-- By tomektom from https://github.com/Alexays/Waybar/issues/3468#issuecomment-2445419416
hl.on("hyprland.shutdown", function()
	hl.exec_cmd("rm ~/.local/share/dbus-1/services/org.kde.kded6.service")
end)

-- Status bar

hl.on("hyprland.start", function()
	hl.exec_cmd(launchprefix .. " /usr/bin/dunst")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd(
		'systemd-inhibit --who="Hyprland config" --why="wlogout keybind" --what=handle-power-key --mode=block sleep infinity & echo $! > /tmp/.hyprland-systemd-inhibit'
	)
	hl.exec_cmd("bluetoothctl power off")
	hl.exec_cmd("~/scripts/hypr/idleInhibitManager.fish")
	hl.exec_cmd(launchprefix .. " ~/.local/bin/clipse -listen")
	hl.exec_cmd("brightnessctl --restore")
	hl.exec_cmd(launchprefix .. " " .. hyprnim .. " watch")
	hl.exec_cmd(hyprnim .. " monitors")
	hl.exec_cmd(
		launchprefix
			.. " kitty --single-instance --class=nvim --hold --override confirm_os_window_close=0 -- fish -c orgfiles",
		{ workspace = "special silent" }
	)
	hl.exec_cmd(
		'printf "[D-BUS Service]\\nName=org.kde.kded6\\nExec=/bin/false" > ~/.local/share/dbus-1/services/org.kde.kded6.service'
	)
	hl.exec_cmd(launchprefix .. " waybar")
	hl.exec_cmd("~/scripts/hypr/events/onUnlock.sh")
end)
