-- See https://wiki.hyprland.org/Configuring/Binds/ and https://wiki.hyprland.org/Configuring/Keywords/
--
-- Flags
-- l -> locked, will also work when an input inhibitor (e.g. a lockscreen) is active.
-- r -> release, will trigger on release of a key.
-- c -> click, will trigger on release of a key or button as long as the mouse cursor stays inside input:drag_threshold.
-- g -> drag, will trigger on release of a key or button as long as the mouse cursor moves outside input:drag_threshold.
-- o -> longPress, will trigger on long press of a key.
-- e -> repeat, will repeat when held.
-- n -> non-consuming, key/mouse events will be passed to the active window in addition to triggering the dispatcher.
-- m -> mouse, see below.
-- t -> transparent, cannot be shadowed by other binds.
-- i -> ignore mods, will ignore modifiers.
-- s -> separate, will arbitrarily combine keys between each mod/key, see [Keysym combos](#keysym-combos) above.
-- d -> has description, will allow you to write a description for your bind.
-- p -> bypasses the app's requests to inhibit keybinds.
-- u -> submap universal, will be active no matter the submap
--
-- Letters that haven't been binded: u, a, z, v, x, q, o
-- Letters that have been binded: W, S, H, L, P, R, G, N, X, Q, B, E, T, F
--
-- wev = see key names
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/core/common.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.common")

local appmenu = "~/scripts/hypr/appmenu.fish" -- app launcher/runner
local powermenu = "~/scripts/hypr/powermenu.sh"

local emojipicker = "pkill fuzzel || bemoji --noline --clip"

local colorpicker = launchprefix .. " fish -c 'kcolorchooser --color (wl-paste) --print | wl-copy --trim-newline'"
local clipboard = launchprefix .. " kitty --single-instance --class=clipse --override confirm_os_window_close=0 clipse"
local terminal = launchprefix .. " kitty --single-instance"
local filemanagerRaw = "YAZI_RESTORE=1 "
	.. launchprefix
	.. " kitty --single-instance --class=yazi --override confirm_os_window_close=0 -- yazi"
local filemanager = '~/scripts/hypr/focusOrLaunch.fish -c yazi -l "' .. filemanagerRaw .. '"'
local browserRaw = launchprefix .. " zen-browser"
local browser = '~/scripts/hypr/focusOrLaunch.fish -c zen -l "' .. browserRaw .. '"'
local musicRaw = launchprefix .. " zen-browser --new-window https://music.youtube.com/"
local music = '~/scripts/hypr/focusOrLaunch.fish -e "YouTube Music — Zen Browser" -l "' .. musicRaw .. '"'
local mail = '~/scripts/hypr/focusOrLaunch.fish -c aerc -l "'
	.. launchprefix
	.. ' kitty --single-instance --class=aerc --override confirm_os_window_close=0 aerc"'
local calculator = '~/scripts/hypr/focusOrLaunch.fish -c org.kde.kalk -l "' .. launchprefix .. ' kalk"'
local wifi = "networkmanager_dmenu"
local calendar = '~/scripts/hypr/focusOrLaunch.fish -c khal -l "'
	.. launchprefix
	.. ' kitty --single-instance --class=khal --override confirm_os_window_close=0 ikhal"'
local traymenu = '~/scripts/hypr/focusOrLaunch.fish -c tray-tui -l "'
	.. launchprefix
	.. ' kitty --single-instance --class=tray-tui --override confirm_os_window_close=0 tray-tui"'

hl.bind(mainmod .. " + backspace", hl.dsp.submap("binds-inhibited"))
hl.define_submap("binds-inhibited", function()
	hl.bind(mainmod .. " + backspace", hl.dsp.submap("reset"))
end)

hl.bind(mainmod .. " + t", hl.dsp.exec_cmd(terminal))
hl.bind(mainmod .. " + e", hl.dsp.exec_cmd(filemanager))
hl.bind(mainmod .. " + SHIFT + e", hl.dsp.exec_cmd(filemanagerRaw))
hl.bind(mainmod .. " + b", hl.dsp.exec_cmd(browser))
hl.bind(mainmod .. " + SHIFT + b", hl.dsp.exec_cmd(browserRaw))
hl.bind(mainmod .. " + c", hl.dsp.exec_cmd(calendar))
hl.bind(mainmod .. " + m", hl.dsp.exec_cmd(mail))
hl.bind(mainmod .. " + SHIFT + c", hl.dsp.exec_cmd(colorpicker))
hl.bind(mainmod .. " + xf86audioplay", hl.dsp.send_shortcut({ mods = "alt", key = "5", window = "class:zen" }))
hl.bind(mainmod .. " + xf86audioplay", hl.dsp.focus({ window = "class:zen" }))
hl.bind("xf86tools", hl.dsp.exec_cmd(music))
hl.bind(mainmod .. " + F11", hl.dsp.exec_cmd(calculator))

hl.bind(mainmod .. " + n", hl.dsp.exec_cmd("~/scripts/hypr/nvim-everywhere.fish"))

hl.bind(mainmod .. " + Pause", hl.dsp.exec_cmd(powermenu), { locked = true })
hl.bind(mainmod .. " + space", hl.dsp.exec_cmd(appmenu))
hl.bind(mainmod .. " + period", hl.dsp.exec_cmd(emojipicker))
hl.bind(mainmod .. " + bar", hl.dsp.exec_cmd(clipboard))
hl.bind("xf86poweroff", hl.dsp.exec_cmd(powermenu), { locked = true })

hl.bind(mainmod .. " + SHIFT + t", hl.dsp.exec_cmd(traymenu))

hl.bind(mainmod .. " + ntilde", hl.dsp.submap("connect-menu"))
hl.define_submap("connect-menu", "reset", function()
	hl.bind("b", hl.dsp.exec_cmd("~/scripts/hypr/bluetooth.fish"))
	hl.bind("w", hl.dsp.exec_cmd(wifi))
	hl.bind("catchall", hl.dsp.submap("reset"))
end)

hl.bind("caps_lock", hl.dsp.exec_cmd("kill -SIGRTMIN+3 $(pgrep waybar)"), {
	locked = true,
	release = true,
	non_consuming = true,
	transparent = true,
	ignore_mods = true,
	submap_universal = true,
})
hl.bind("num_lock", hl.dsp.exec_cmd("kill -SIGRTMIN+4 $(pgrep waybar)"), {
	locked = true,
	release = true,
	non_consuming = true,
	transparent = true,
	ignore_mods = true,
	submap_universal = true,
})
hl.bind(
	"xf86touchpadon",
	hl.dsp.exec_cmd("~/scripts/waybar/touchpad_status.fish on"),
	{ locked = true, non_consuming = true, transparent = true, ignore_mods = true, submap_universal = true }
)
hl.bind(
	"xf86touchpadoff",
	hl.dsp.exec_cmd("~/scripts/waybar/touchpad_status.fish off"),
	{ locked = true, non_consuming = true, transparent = true, ignore_mods = true, submap_universal = true }
)

hl.bind(mainmod .. " + SHIFT + n", hl.dsp.submap("notifications"))
hl.define_submap("notifications", function()
	hl.bind("d", hl.dsp.exec_cmd("dunstctl close"))

	hl.bind("SHIFT + d", hl.dsp.exec_cmd("dunstctl close-all"))
	hl.bind("SHIFT + d", hl.dsp.submap("reset"))

	hl.bind("p", hl.dsp.exec_cmd("dunstctl history-pop"))

	hl.bind("l", hl.dsp.exec_cmd("dunstctl action"))
	hl.bind("l", hl.dsp.submap("reset"))

	hl.bind("y", hl.dsp.exec_cmd("printf %s $(cat $HOME/.config/dunst/body.tmp) | wl-copy"))
	hl.bind("y", hl.dsp.submap("reset"))

	hl.bind("catchall", hl.dsp.submap("reset"), { release = true })
end)

local screenshotcmd = "grimblast --notify --openparentdir copysave"

hl.bind("print", hl.dsp.exec_cmd(screenshotcmd .. " screen"), { locked = true })
hl.bind(mainmod .. " + print", hl.dsp.exec_cmd(screenshotcmd .. " active"), { locked = true })
hl.bind("SHIFT + print", hl.dsp.exec_cmd(screenshotcmd .. " area"), { locked = true })

local function layout_bind(bind_table)
	return function()
		local workspace = hl.get_active_special_workspace() or hl.get_active_workspace()

		if not workspace then
			return
		end

		local layout = workspace.tiled_layout

		if bind_table[layout] then
			hl.dispatch(bind_table[layout])
		end
	end
end

hl.bind(
	mainmod .. " + SHIFT + p",
	layout_bind({
		dwindle = hl.dsp.layout("togglesplit"),
		master = hl.dsp.layout("orientationnext"),
		scrolling = hl.dsp.layout("consume_or_expel next"),
	})
)

hl.bind(mainmod .. " + y", function()
	local layouts = { "scrolling", "dwindle", "master" } -- "monocle"
	local workspace = hl.get_active_workspace()
	if hl.get_active_special_workspace() then
		workspace = hl.get_active_special_workspace()
	end

	local next_layout = "dwindle"

	if not workspace then
		return
	end

	for i = 1, #layouts do
		if layouts[i] == workspace.tiled_layout then
			local next_layout_idx = (i % #layouts) + 1
			next_layout = layouts[next_layout_idx]
			break
		end
	end

	if workspace.special then
		hl.workspace_rule({ workspace = tostring(workspace.name), layout = next_layout })
	else
		hl.workspace_rule({ workspace = tostring(workspace.id), layout = next_layout })
	end
end)
local soundstep = 0.05 -- 5%
local soundbigstep = 0.2 -- 20%
local soundsmallstep = 0.01 -- 1%

local soundup = "~/scripts/hypr/audiocontrol.fish +" .. soundstep
local sounddown = "~/scripts/hypr/audiocontrol.fish -" .. soundstep

local soundbigup = "~/scripts/hypr/audiocontrol.fish +" .. soundbigstep
local soundbigdown = "~/scripts/hypr/audiocontrol.fish -" .. soundbigstep

local soundsmallup = "~/scripts/hypr/audiocontrol.fish +" .. soundsmallstep
local soundsmalldown = "~/scripts/hypr/audiocontrol.fish -" .. soundsmallstep

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd(soundup), { locked = true, repeating = true })
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd(sounddown), { locked = true, repeating = true })
hl.bind("SHIFT + xf86audioraisevolume", hl.dsp.exec_cmd(soundbigup), { locked = true, repeating = true })
hl.bind("SHIFT + xf86audiolowervolume", hl.dsp.exec_cmd(soundbigdown), { locked = true, repeating = true })
hl.bind("CTRL + xf86audioraisevolume", hl.dsp.exec_cmd(soundsmallup), { locked = true, repeating = true })
hl.bind("CTRL + xf86audiolowervolume", hl.dsp.exec_cmd(soundsmalldown), { locked = true, repeating = true })

hl.bind(mainmod .. " + up", hl.dsp.exec_cmd(soundup), { locked = true, repeating = true })
hl.bind(mainmod .. " + down", hl.dsp.exec_cmd(sounddown), { locked = true, repeating = true })
hl.bind(mainmod .. " + SHIFT + up", hl.dsp.exec_cmd(soundbigup), { locked = true, repeating = true })
hl.bind(mainmod .. " + SHIFT + down", hl.dsp.exec_cmd(soundbigdown), { locked = true, repeating = true })
hl.bind(mainmod .. " + CTRL + up", hl.dsp.exec_cmd(soundsmallup), { locked = true, repeating = true })
hl.bind(mainmod .. " + CTRL + down", hl.dsp.exec_cmd(soundsmalldown), { locked = true, repeating = true })

hl.bind(
	"xf86audiomute",
	hl.dsp.exec_cmd("~/scripts/hypr/audiocontrol.fish toggle"),
	{ locked = true, repeating = true }
)

hl.bind(
	"xf86audiomicmute",
	hl.dsp.exec_cmd("~/scripts/hypr/miccontrol.fish toggle"),
	{ locked = true, repeating = true }
)

local brightnessbigstep = "20%"
local brightnessstep = "5%"
local brightnesssmallstep = "1%"

local brightnessup = "brightnessctl s +" .. brightnessstep
local brightnessdown = "brightnessctl s " .. brightnessstep .. "-"

local brightnessbigup = "brightnessctl s +" .. brightnessbigstep
local brightnessbigdown = "brightnessctl s " .. brightnessbigstep .. "-"

local brightnesssmallup = "brightnessctl s +" .. brightnesssmallstep
local brightnesssmalldown = "brightnessctl s " .. brightnesssmallstep .. "-"

hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd(brightnessdown), { locked = true, repeating = true })
hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd(brightnessup), { locked = true, repeating = true })
hl.bind("SHIFT + xf86monbrightnessdown", hl.dsp.exec_cmd(brightnessbigdown), { locked = true, repeating = true })
hl.bind("SHIFT + xf86monbrightnessup", hl.dsp.exec_cmd(brightnessbigup), { locked = true, repeating = true })
hl.bind("CTRL + xf86monbrightnessdown", hl.dsp.exec_cmd(brightnesssmalldown), { locked = true, repeating = true })
hl.bind("CTRL + xf86monbrightnessup", hl.dsp.exec_cmd(brightnesssmallup), { locked = true, repeating = true })

hl.bind(mainmod .. " + left", hl.dsp.exec_cmd(brightnessdown), { locked = true, repeating = true })
hl.bind(mainmod .. " + right", hl.dsp.exec_cmd(brightnessup), { locked = true, repeating = true })
hl.bind(mainmod .. " + SHIFT + left", hl.dsp.exec_cmd(brightnessbigdown), { locked = true, repeating = true })
hl.bind(mainmod .. " + SHIFT + right", hl.dsp.exec_cmd(brightnessbigup), { locked = true, repeating = true })
hl.bind(mainmod .. " + CTRL + left", hl.dsp.exec_cmd(brightnesssmalldown), { locked = true, repeating = true })
hl.bind(mainmod .. " + CTRL + right", hl.dsp.exec_cmd(brightnesssmallup), { locked = true, repeating = true })

hl.bind("xf86audionext", hl.dsp.exec_cmd("~/scripts/hypr/playNext.fish"), { locked = true })
hl.bind("xf86audioprev", hl.dsp.exec_cmd("~/scripts/hypr/playPrev.fish"), { locked = true })
hl.bind("xf86audiopause", hl.dsp.exec_cmd("~/scripts/hypr/playPause.fish"), { locked = true })
hl.bind("xf86audioplay", hl.dsp.exec_cmd("~/scripts/hypr/playPause.fish"), { locked = true })

hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("~/scripts/hypr/events/onLidClose.fish"), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("~/scripts/hypr/events/onLidOpen.fish"), { locked = true })

local MAX_ZOOM = 4
local MIN_ZOOM = 1
local ZOOM_TOGGLE_FACTOR = 1.5

---@param offset number
---@return nil
local function zoom(offset)
	local current = hl.get_config("cursor.zoom_factor")
	if offset ~= nil then
		current = current + offset
	elseif current ~= MIN_ZOOM then
		current = MIN_ZOOM
	else
		current = ZOOM_TOGGLE_FACTOR
	end
	current = math.max(MIN_ZOOM, math.min(MAX_ZOOM, current))
	hl.config({ cursor = { zoom_factor = current } })
end

hl.bind(mainmod .. " + mouse_down", function()
	zoom(0.5)
end)
hl.bind(mainmod .. " + mouse_up", function()
	zoom(-0.5)
end)

hl.bind(mainmod .. " + minus", function()
	zoom(-0.5)
end)
hl.bind(mainmod .. " + plus", function()
	zoom(0.5)
end)

hl.bind(mainmod .. " + kp_subtract", function()
	zoom(-0.5)
end)
hl.bind(mainmod .. " + kp_add", function()
	zoom(0.5)
end)
-- hl.bind(mainmod .. " + equal", zoom) -- you can't really trigger this bind since equal is shift+0 which actually triggers move window to 10th workspace

hl.bind(mainmod .. " + CTRL + escape", hl.dsp.exec_cmd("killall waybar || waybar"))

hl.bind(mainmod .. " + SHIFT + x", hl.dsp.exec_cmd("~/scripts/hypr/toggleEffects.sh"))

hl.bind(mainmod .. " + SHIFT + r", hl.dsp.exec_cmd("hyprctl reload"), { locked = true })

hl.bind(mainmod .. " + f5", hl.dsp.exec_cmd("$hyprnim monitors --all"), { locked = true })
hl.bind(mainmod .. " + f6", hl.dsp.exec_cmd("$hyprnim monitors"), { locked = true })

hl.bind("mouse:273", hl.dsp.exec_cmd("~/scripts/hypr/desktopRightClick.fish"), { non_consuming = true })

hl.bind(mainmod .. " + apostrophe", hl.dsp.exec_cmd("~/scripts/hypr/cycleShaders.fish"), { locked = true })
hl.bind(mainmod .. " + SHIFT + apostrophe", hl.dsp.exec_cmd("~/scripts/hypr/cycleShaders.fish -1"), { locked = true })

hl.bind(mainmod .. " + i", hl.dsp.exec_cmd("~/scripts/hypr/toggleIdleInhibit.fish"))

-- DONE: manual review on line 261 — changegroupactive: expected 'f', 'b', or an index (got "")
hl.bind(mainmod .. " + CTRL + l", hl.dsp.group.next())
hl.bind(mainmod .. " + CTRL + h", hl.dsp.group.prev())

hl.bind(mainmod .. " + SHIFT + g", hl.dsp.group.toggle())

local function enable_group()
	local active_window = hl.get_active_window()
	if active_window and not active_window.group then
		hl.dispatch(hl.dsp.group.toggle())
	end
end

hl.bind(mainmod .. " + g", function()
	enable_group()
end)
hl.bind(mainmod .. " + g", hl.dsp.submap("group"))
hl.define_submap("group", function()
	hl.bind("g", hl.dsp.group.toggle())
	hl.bind("c", hl.dsp.group.lock_active({ action = "toggle" }))

	hl.bind("SHIFT + l", hl.dsp.window.move({ direction = "r", group_aware = true }))
	hl.bind("SHIFT + h", hl.dsp.window.move({ direction = "l", group_aware = true }))
	hl.bind("SHIFT + j", hl.dsp.window.move({ direction = "d", group_aware = true }))
	hl.bind("SHIFT + k", hl.dsp.window.move({ direction = "u", group_aware = true }))

	hl.bind(
		"h",
		layout_bind({
			dwindle = hl.dsp.focus({ direction = "left" }),
			master = hl.dsp.focus({ direction = "left" }),
			scrolling = hl.dsp.layout("focus l"),
		})
	)
	hl.bind(
		"l",
		layout_bind({
			dwindle = hl.dsp.focus({ direction = "right" }),
			master = hl.dsp.focus({ direction = "right" }),
			scrolling = hl.dsp.layout("focus r"),
		})
	)
	hl.bind("k", hl.dsp.focus({ direction = "up" }))
	hl.bind("j", hl.dsp.focus({ direction = "down" }))

	hl.bind("h", function()
		enable_group()
	end)
	hl.bind("l", function()
		enable_group()
	end)
	hl.bind("k", function()
		enable_group()
	end)
	hl.bind("j", function()
		enable_group()
	end)

	hl.bind("CTRL + h", hl.dsp.window.move({ direction = "l" }))
	hl.bind("CTRL + j", hl.dsp.window.move({ direction = "d" }))
	hl.bind("CTRL + k", hl.dsp.window.move({ direction = "u" }))
	hl.bind("CTRL + l", hl.dsp.window.move({ direction = "r" }))

	hl.bind("catchall", hl.dsp.submap("reset"), { release = true })
end)

hl.bind(mainmod .. " + SHIFT + q", hl.dsp.window.kill())
hl.bind(mainmod .. " + d", hl.dsp.window.close())

hl.bind(
	mainmod .. " + p",
	layout_bind({
		dwindle = hl.dsp.window.swap({ next = true }),
		master = hl.dsp.window.swap({ next = true }),
		scrolling = hl.dsp.layout("swapcol r"),
	})
)

hl.bind("ALT + tab", hl.dsp.focus({ last = true }))

hl.bind(
	mainmod .. " + f",
	layout_bind({
		dwindle = hl.dsp.window.cycle_next({ floating = true, tiled = true }),
		master = hl.dsp.window.cycle_next({ floating = true, tiled = true }),
		scrolling = hl.dsp.window.cycle_next({ floating = true, tiled = true }),
		-- monocle = hl.dsp.window.cycle_next({ tiled = true }),
	})
)
hl.bind(
	mainmod .. " + f",
	layout_bind({
		dwindle = hl.dsp.window.alter_zorder({ mode = "top" }),
		master = hl.dsp.window.alter_zorder({ mode = "top" }),
		scrolling = hl.dsp.window.alter_zorder({ mode = "top" }),
	})
)
hl.bind(
	mainmod .. " + SHIFT + f",
	layout_bind({
		dwindle = hl.dsp.window.cycle_next({ next = false, floating = true, tiled = true }),
		master = hl.dsp.window.cycle_next({ next = false, floating = true, tiled = true }),
		scrolling = hl.dsp.window.cycle_next({ next = false, floating = true, tiled = true }),
		-- monocle = hl.dsp.window.cycle_next({ tiled = true }),
	})
)
hl.bind(
	mainmod .. " + SHIFT + f",
	layout_bind({
		dwindle = hl.dsp.window.alter_zorder({ mode = "top" }),
		master = hl.dsp.window.alter_zorder({ mode = "top" }),
		scrolling = hl.dsp.window.alter_zorder({ mode = "top" }),
	})
)

hl.bind(
	mainmod .. " + h",
	layout_bind({
		dwindle = hl.dsp.focus({ direction = "left" }),
		master = hl.dsp.focus({ direction = "left" }),
		scrolling = hl.dsp.layout("focus l"),
	})
)
hl.bind(
	mainmod .. " + l",
	layout_bind({
		dwindle = hl.dsp.focus({ direction = "right" }),
		master = hl.dsp.focus({ direction = "right" }),
		scrolling = hl.dsp.layout("focus r"),
	})
)
hl.bind(mainmod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainmod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainmod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainmod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainmod .. " + w", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainmod .. " + SHIFT + w", hl.dsp.window.pseudo())

hl.bind("f11", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

local resize_step = 99 -- 1920 / 20
local resize_big_step = 220 -- 1980 / 8
local resize_small_step = 20 -- 1980 / 99

hl.bind(mainmod .. " + r", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
	hl.bind("h", hl.dsp.window.resize({ x = -resize_step, y = 0, relative = true }), { repeating = true })
	hl.bind("l", hl.dsp.window.resize({ x = resize_step, y = 0, relative = true }), { repeating = true })
	hl.bind("k", hl.dsp.window.resize({ x = 0, y = -resize_step, relative = true }), { repeating = true })
	hl.bind("j", hl.dsp.window.resize({ x = 0, y = resize_step, relative = true }), { repeating = true })

	hl.bind("SHIFT + h", hl.dsp.window.resize({ x = -resize_big_step, y = 0, relative = true }), { repeating = true })
	hl.bind("SHIFT + l", hl.dsp.window.resize({ x = resize_big_step, y = 0, relative = true }), { repeating = true })
	hl.bind("SHIFT + k", hl.dsp.window.resize({ x = 0, y = -resize_big_step, relative = true }), { repeating = true })
	hl.bind("SHIFT + j", hl.dsp.window.resize({ x = 0, y = resize_big_step, relative = true }), { repeating = true })

	hl.bind("CTRL + h", hl.dsp.window.resize({ x = -resize_small_step, y = 0, relative = true }), { repeating = true })
	hl.bind("CTRL + l", hl.dsp.window.resize({ x = resize_small_step, y = 0, relative = true }), { repeating = true })
	hl.bind("CTRL + k", hl.dsp.window.resize({ x = 0, y = -resize_small_step, relative = true }), { repeating = true })
	hl.bind("CTRL + j", hl.dsp.window.resize({ x = 0, y = resize_small_step, relative = true }), { repeating = true })

	hl.bind("catchall", hl.dsp.submap("reset"), { release = true })
end)

hl.bind(mainmod .. " + s", hl.dsp.workspace.toggle_special(""))
hl.bind("xf86presentation", hl.dsp.workspace.toggle_special(""))
hl.bind(mainmod .. " + SHIFT + s", hl.dsp.window.move({ workspace = "special" }))

--wSwitch to the next workspace, but if a special workspace is open, close it (and don't switch worspace)
local function switch_workspace(params)
	if hl.get_active_special_workspace() then
		hl.dispatch(hl.dsp.workspace.toggle_special())
		return
	end

	hl.dispatch(hl.dsp.focus(params))
end

hl.bind(mainmod .. " + tab", function()
	switch_workspace({ workspace = "previous" })
end)

hl.bind(mainmod .. " + SHIFT + h", function()
	switch_workspace({ workspace = "e-1" })
end)
hl.bind(mainmod .. " + SHIFT + l", function()
	switch_workspace({ workspace = "e+1" })
end)
hl.bind(mainmod .. " + SHIFT + j", function()
	switch_workspace({ workspace = "-10" })
end)
hl.bind(mainmod .. " + SHIFT + k", function()
	switch_workspace({ workspace = "+10" })
end)

hl.bind(mainmod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainmod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainmod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainmod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainmod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainmod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainmod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainmod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainmod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainmod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainmod .. " + braceleft", hl.dsp.window.move({ workspace = "-1" }))
hl.bind(mainmod .. " + braceright", hl.dsp.window.move({ workspace = "+1" }))

function prequire(...)
	local status, lib = pcall(require, ...)
	if status then
		return lib
	end
	return nil
end

-- 1. Grab the active major/minor Lua version embedded inside Hyprland
local lua_ver = _VERSION:match("%d+%.%d+")

-- 2. Force Hyprland to look inside Arch's system Lua paths and LuaRocks directories
package.path = package.path .. ";/usr/share/lua/" .. lua_ver .. "/?.lua"
package.path = package.path .. ";/usr/share/lua/" .. lua_ver .. "/?/init.lua"
package.path = package.path .. ";/usr/lib/luarocks/rocks-" .. lua_ver .. "/?.lua"

-- 3. Now, you can safely initialize the loader and external packages
prequire("luarocks.loader")
local inspect = prequire("inspect")

function P(a)
	if type(a) == "table" and inspect then
		print(inspect(a))
	else
		print(a)
	end
end

local function swap_workspace(other_workspace_selector)
	local active_window = hl.get_active_window()
	local active_workspace = hl.get_active_workspace()
	local active_windows = hl.get_workspace_windows(active_workspace)

	local other_workspace = hl.get_workspace(other_workspace_selector)

	local other_windows = hl.get_workspace_windows(other_workspace)

	for i, window in pairs(active_windows) do
		-- here we use other_workspace_selector and not other_workspace, as that would fail when swapping to an empty workspace
		hl.dispatch(hl.dsp.window.move({ workspace = other_workspace_selector, follow = false, window = window }))
	end

	for i, window in pairs(other_windows) do
		hl.dispatch(hl.dsp.window.move({ workspace = active_workspace, follow = false, window = window }))
	end

	hl.dispatch(hl.dsp.focus({ window = active_window }))
end

hl.bind(mainmod .. " + SHIFT + braceleft", function()
	swap_workspace("-1")
end)
hl.bind(mainmod .. " + SHIFT + braceright", function()
	swap_workspace("+1")
end)

hl.bind(mainmod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainmod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainmod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainmod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainmod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainmod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainmod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainmod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainmod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainmod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.config({
	binds = {
		hide_special_on_workspace_change = true,
		-- allow_workspace_cycles = true # This is not what I want (firefox behavior of cycling through tabs)
		workspace_center_on = 1,
		movefocus_cycles_fullscreen = true,
		scroll_event_delay = 0,
		focus_preferred_method = 0,
	},
	--################# VARIABLES ##################
	-- --noline -> to prevent a new line at the end
	-- --clip -> to copy the emoji as well
	-- $colorpicker = pkill hyprpicker || hyprpicker --autocopy --format=hex
	-- $coloreditor = $launchprefix kitty --single-instance --class=termpicker --override confirm_os_window_close=0 termpicker
	-- $musicRaw = $launchprefix spotify
	-- $musicRaw = $launchprefix kitty --single-instance --class=spotify_player --override confirm_os_window_close=0 spotify_player
	-- $musicRaw = $launchprefix env 'WINEPREFIX=/home/cristobal/.wine' wine 'C:\\\\users\\\\cristobal\\\\AppData\\\\Roaming\\\\Microsoft\\\\Windows\\\\Start Menu\\\\Programs\\\\iTunes\\\\iTunes.lnk'
	--################# BINDS INHIBITOR ##################
	--################# APPLICATIONS ##################
	-- bind = $mainmod, xf86audioplay, exec, $music
	--################# MENUS ##################
	-- bindl = $mainmod, escape, exec, $powermenu # I end up pressing this on accident
	--################# SYSTEM TRAY MENU? ##################
	-- bind = shift, b, exec, $bluetooth
	--################# KEYBOARD STATE INDICATORS ##################
	-- note that without the r flag, waybar would be updated before the actual toggle happens and it wouldn't work
	--
	--################# TOUCHPAD STATE INDICATORS ##################
	--################# NOTIFICATIONS ##################
	-- printf %s removes the trailing newline
	--################# SCREENSHOTS ##################
	--################# LAYOUT ##################
	-- bind = $mainmod shift, mouse_down, exec, layoutmsg, move +200
	-- bind = $mainmod shift, mouse_up, exec, layoutmsg, move -200
	--################# SOUND ##################
	--################# BRIGHTNESS ##################
	--################# PLAYER CONTROL ##################
	-- bindl = shift, xf86audiopause, exec, playerctl play-pause
	-- bindl = shift, xf86audioplay, exec, playerctl play-pause
	-- bindl = shift, xf86audionext, exec, playerctl next
	-- bindl = shift, xf86audioprev, exec, playerctl previous
	--################# LAPTOP LID ##################
	--################# ZOOM ##################
	-- NOTE: Doesn't really work but you can just zoom out...
	--################# HYPR ##################
	-- bind = $mainmod, m, exec, ~/scripts/hypr/onExit.sh && uwsm stop # Exit hyprland
	-- bindl = $mainmod, f6, exec, $hyprnim monitors --disableEnable
	--################# GROUPS ##################
	--################# WINDOWS ##################
	-- bind = $mainmod ctrl, h, swapnext, prev
	-- bind = $mainmod ctrl, l, swapnext
	-- TODO: make y cycle between layouts
	-- Move/resize windows with mainMod + LMB/RMB and dragging
	-- bind = $mainmod, f, fullscreen
	-- bind = $mainmod, backspace, toggleswallow
	--################# WINDOW RESIZE ##################
	--################# WORKSPACES ##################
	-- bind = $mainmod shift, braceleft, movetoworkspace, -10
	-- bind = $mainmod shift, braceright, movetoworkspace, +10
	-- TODO: make '$maindmod ctrl, braceleft work' and add bindings to move workspace to a specific id
	--################# HYPREXPO ##################
	-- bind = $mainmod, o, hyprexpo:expo, toggle
})
