-- Based off https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/wallust/wallust-hyprland.conf

-- scheme: "carbonfox"
-- author: "EdenEast"
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

Background = "rgb(161616)"
Foreground = "rgb(f2f4f8)"
Color0 = "rgb(161616)"
Color1 = "rgb(252525)"
Color2 = "rgb(353535)"
Color3 = "rgb(484848)"
Color4 = "rgb(7b7c7e)"
Color5 = "rgb(f2f4f8)"
Color6 = "rgb(b6b8bb)"
Color7 = "rgb(e4e4e5)"
Color8 = "rgb(ee5396)"
Color9 = "rgb(3ddbd9)"
Color10 = "rgb(08bdba)"
Color11 = "rgb(25be6a)"
Color12 = "rgb(33b1ff)"
Color13 = "rgb(78a9ff)"
Color14 = "rgb(be95ff)"
Color15 = "rgb(ff7eb6)"

Unlockedgroupbar = "be95ff"
Lockedgroupbar = "a269ff"

-- $Background = rgb(010102)
-- $Foreground = rgb(FDF8FE)
-- $Color0 = rgb(313131)
-- $Color1 = rgb(09050C)
-- $Color2 = rgb(221647)
-- $Color3 = rgb(2C1A40)
-- $Color4 = rgb(5E3887)
-- $Color5 = rgb(7344A6)
-- $Color6 = rgb(BAB0BD)
-- $Color7 = rgb(F3ECF5)
-- $Color8 = rgb(AAA5AC)
-- $Color9 = rgb(0B0711)
-- $Color10 = rgb(2D1D5F)
-- $Color11 = rgb(3B2355)
-- $Color12 = rgb(7D4AB4)
-- $Color13 = rgb(9A5BDD)
-- $Color14 = rgb(F8EAFC)
-- $Color15 = rgb(F3ECF5)
