-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

Mainmod = "SUPER" -- Windows key

Launchprefix = "app2unit -- "
Openeffect = "quickshell ipc call main triggerGlow "
Openprefix = Openeffect .. "&& " .. Launchprefix

-- hyprnim = "~/.nimble/bin/hyprnim"

Bordersize = 1
