-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    cursor = {
        inactive_timeout = 5,
        -- hide_on_key_press = true
        -- For lagging mouse
        no_hardware_cursors = 1,
        use_cpu_buffer = 0,
        zoom_disable_aa = false,
        zoom_detached_camera = false,
    },
})

