-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
require("core.colors")

-- https://wiki.hyprland.org/Configuring/Variables/#general
hl.config({
	general = {
		gaps_in = 6,
		gaps_out = { top = 10, right = 18, bottom = 18, left = 18 }, -- 10 to compensate for waybar (though waybar actually is 28 pixels tall so 🤷)
		border_size = 0,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		col = {
			active_border = color9,
			inactive_border = color4,
		},
		resize_on_border = true, -- Set to true enable resizing windows by clicking and dragging on borders and gaps
		hover_icon_on_border = true,
		allow_tearing = false, -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		layout = "dwindle",
		no_focus_fallback = false,
		snap = {
			enabled = true,
			respect_gaps = true,
		},
	},
})
