-- https://wiki.hypr.land/Configuring/Gestures/
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

require("core.common")

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})
hl.config({
	gestures = {
		workspace_swipe_forever = true,
		workspace_swipe_direction_lock = false,
		workspace_swipe_distance = 200,
	},
})

-- just outright hard to do, just use mainmod + plus/minus
-- hl.gesture({ fingers = 2, direction = "pinch", mods = mainmod, action = "cursorZoom", zoom_level = 1, mode = "live" })
