# https://wiki.hyprland.org/Configuring/Variables/#gestures
gestures {
    workspace_swipe = true
    workspace_swipe_distance = 80
    workspace_swipe_forever = true
    workspace_swipe_direction_lock = false
}
