-- Generated by hyprlang2lua. Review TODOs before reloading
-- Source: ~/.config/hypr/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("core.colors")

hl.config({
	group = {
		col = {
			border_active = Color14,
			border_locked_active = Color15,
			border_inactive = Color4,
			border_locked_inactive = Color4,
		},
		groupbar = {
			enabled = true,
			keep_upper_gap = false,
			render_titles = false,
			indicator_height = 2,
			gaps_out = 2,
			gaps_in = 4,
			rounding = 10,
			col = {
				active = "rgba(" .. Unlockedgroupbar .. "ff)",
				inactive = "rgba(" .. Unlockedgroupbar .. "77)",
				locked_active = "rgba(" .. Lockedgroupbar .. "ff)",
				locked_inactive = "rgba(" .. Lockedgroupbar .. "77)",
			},
		},
	},
})
