source = ~/.config/hypr/colors.conf

group {
    col.border_active = $color14
    col.border_locked_active = $color15
    col.border_inactive = $color4
    col.border_locked_inactive = $color4

	groupbar {
        enabled = false
        keep_upper_gap = false
        render_titles = false
		col.active = $color0
  }
}
