source = ~/.config/hypr/colors.conf

group {
    col.border_active = $color14
    col.border_locked_active = $color15
    col.border_inactive = $color4
    col.border_locked_inactive = $color4

	groupbar {
        enabled = true
        keep_upper_gap = false
        render_titles = false
        indicator_height = 2
		col.active = rgba(be95ffff)
		col.inactive = rgba(be95ff77)
        rounding = 10
  }
}
