-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
	dwindle = {
		-- pseudotile = true # Master switch for pseudotiling.
		preserve_split = true,
		-- special_scale_factor = 0.85,
		precise_mouse_move = true,
	},
	master = {},
	scrolling = {
		wrap_focus = true,
	},
})
