-- See https://wiki.hyprland.org/Configuring/Monitors/
-- This was generated automatically by /home/cristobal/dev/hyprnim/src/hyprnim/monitors.nim
-- Default config for the defined monitors:
-- monitor = desc:Chimei Innolux Corporation 0x1521, 1920x1080@144.00Hz, auto, 1
-- monitor = desc:YSP MF215BH 0x00001A0A, 1920x1080@60.00Hz, auto, 1
-- monitor = desc:Samsung Electric Company SAMSUNG 0x01000E00, 2560x1440@59.95Hz, auto, 1

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

hl.monitor({
	output = "desc:Chimei Innolux Corporation 0x1521",
	mode = "1920x1080@144.00Hz",
	position = "auto",
	scale = "1",
})
