-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
-- Super big gaps on special workspace
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
	workspace = "s[true]",
	gaps_out = 100,
})

-- workspace = 10, layout:scrolling
