# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-dragging-issues
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:pin = false
  match:fullscreen = false

  no_focus = on
}
