# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Only show borders on groupped windows
# windowrule = noborder, group:0

# For special workspace
#windowrule = noborder, onworkspace:s[true], group:0

# Don't show border on windows when they're the only one in a workspace
#windowrule = noborder, onworkspace:w[1], group:0
