$floorpPasswordDialog = Password Required.*Floorp
windowrule = match:class floorp, float on, match:title $floorpPasswordDialog
windowrule = match:class floorp, dim_around on, match:title $floorpPasswordDialog
windowrule = match:class floorp, border_size 1, match:title $floorpPasswordDialog

windowrule = match:class floorp, match:title Library, float on
