$floorpPasswordDialog = Password Required.*Floorp
windowrule = float, title:$floorpPasswordDialog, class:floorp
windowrule = dimaround, title:$floorpPasswordDialog, class:floorp
# Show border (does it work?...)
windowrule = noborder on, title:$floorpPasswordDialog, class:floorp

windowrule = float, class:floorp, title:Library
