windowrule = float, class:nvim-everywhere
windowrule = size 45% 30%, class:nvim-everywhere
windowrule = dimaround, class:nvim-everywhere
# windowrule = move onscreen cursor -50% 0%, class:nvim-everywhere
