source = ~/.config/hypr/core/common.conf

windowrule = match:class nvim-everywhere, float on
windowrule = match:class nvim-everywhere, size 45% 30%
# windowrule = match:class nvim-everywhere, border_size $bordersize
windowrule = match:class nvim-everywhere, dim_around on
# windowrule = match:class nvim-everywhere, move onscreen cursor -50% 0%
