windowrule = match:class showmethekey-gtk, float on
windowrule = match:class showmethekey-gtk, persistent_size on
windowrule = match:class showmethekey-gtk, move 100%-w-20
windowrule = match:class showmethekey-gtk, no_initial_focus on
windowrule = match:class showmethekey-gtk, size 30% 5%
windowrule = match:class showmethekey-gtk, pin on
windowrule = match:class showmethekey-gtk, no_follow_mouse on
