windowrule = float, class:showmethekey-gtk
windowrule = persistentsize, class:showmethekey-gtk
windowrule = move 100%-w-20, class:showmethekey-gtk
windowrule = noinitialfocus, class:showmethekey-gtk
windowrule = pin, class:showmethekey-gtk
# at 1197,996
# size 704,6s5
