# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

# Autostart Polkit (to manage system-wide privileges)
exec-once=/usr/lib/polkit-kde-authentication-agent-1

# Autostart dunst (notificiation daemon, manages system notifications)
exec-once=/usr/bin/dunst

# Status bar
exec-once=waybar

# Clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Idle manager
exec-once = hypridle

# Wallpaper
exec-once = hyprpaper

# Gamma/temperature filter
exec-once = hyprsunset
