# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

source = ~/.config/hypr/core/*
source = ~/.config/hypr/extra/rules/*
source = ~/.config/hypr/extra/plugins.conf

# opengl:nvidia_anti_flicker = false # reduces flickering on nvidia at the cost of possible frame drops on lower-end GPUs. On non-nvidia, this is ignored.

# https://wiki.hyprland.org/Configuring/Environment-variables/
# They're in:
# ~/.config/uwsm/env
# ~/.config/uwsm/env-hyprland
