general {
    lock_cmd = pidof hyprlock || hyprlock # command executed when a session lock is detected
    before_sleep_cmd = ~/.config/hypr/scripts/lock.sh # lock before suspend.
    on_unlock_cmd = ~/.config/hypr/scripts/on_events/onUnlock.sh
    on_lock_cmd = ~/.config/hypr/scripts/on_events/onLock.sh
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
}
# Dim screen
listener {
    timeout = 60 # 1min.
    on-timeout = brightnessctl s 15%-
    on-resume = brightnessctl s +15%
}

# Lock screen
listener {
    timeout = 180 # 3min
    on-timeout = ~/.config/hypr/scripts/wlogout/lock.sh 
}

# Turn screen off
listener {
    timeout = 240 # 4min
    on-timeout = hyprctl dispatch dpms off 
    on-resume = hyprctl dispatch dpms on 
}

# Suspend PC
listener {
    timeout = 600 # 10min
    on-timeout = ~/.config/hypr/scripts/wlogout/suspend.sh 
}
