general {
    lock_cmd = pidof hyprlock || hyprlock # command executed when a session lock is detected
    before_sleep_cmd = ~/scripts/hypr/lock.sh # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
}
# Dim screen
listener {
    timeout = 60 # 1min.
    on-timeout = ~/.nimble/bin/hyprnim d1.5
    on-resume = ~/.nimble/bin/hyprnim x1.5
}

# Lock screen
listener {
    timeout = 120 # 2min
    on-timeout = ~/scripts/hypr/lock.sh 
}

# Turn screen off
listener {
    timeout = 180 # 3min
    on-timeout = hyprctl dispatch dpms off 
    on-resume = hyprctl dispatch dpms on 
}

# Suspend PC
listener {
    timeout = 600 # 10min
    on-timeout = ~/scripts/hypr/suspend.sh 
}
