general {
    lock_cmd = ~/scripts/hypr/lock.sh
    before_sleep_cmd = loginctl lock-session # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on # to avoid having to press a key twice to turn on the display.
}
 # TODO: use a script not brightnessctl
listener {
    timeout = 60 # 1min.
    on-timeout = brightnessctl -s set 50
    on-resume = brightnessctl -r
}

listener {
    timeout = 180 # 3min
    on-timeout = ~/scripts/hypr/lock.sh # lock screen when timeout has passed
}

listener {
    timeout = 300 # 5min
    on-timeout = hyprctl dispatch dpms off # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 900 # 30min
    on-timeout = ~/scripts/hypr/suspend.sh # suspend pc
}
