# See https://wiki.hyprland.org/Configuring/Monitors/
# This was generated automatically by /home/cristobal/scripts/hypr/reloadMonitors.nim
monitor = desc:Chimei Innolux Corporation 0x1521, disable
monitor = desc:YSP MF215BH 0x00001A0A, 1920x1080@60.00Hz, auto, 1
