# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
source = ~/.config/hypr/colors.conf

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# NOTE: provisional
windowrule = noborder, group:0

# For special workspace
windowrule = noborder, onworkspace:s[true], group:0

# Don't show border on windows when they're the only one in a workspace
windowrule = noborder, onworkspace:w[1], group:0

windowrule = noborder, class:yazi, group:0
windowrule = rounding 5, class:yazi

windowrule = float, class:nvim-everywhere
windowrule = size 45% 30%, class:nvim-everywhere
windowrule = dimaround, class:nvim-everywhere
# windowrule = move onscreen cursor -50% 0%, class:nvim-everywhere

# windowrulev2 = noborder, title:.*lazygit.*, group:0

$floorpPasswordDialog = Password Required.*Floorp
windowrule = float, title:$floorpPasswordDialog, class:floorp
windowrule = dimaround, title:$floorpPasswordDialog, class:floorp
# Show border (does it work?...)
windowrule = noborder on, title:$floorpPasswordDialog, class:floorp

windowrule = float, class:floorp, title:Library

windowrule = float, class:org.pulseaudio.pavucontrol
windowrule = size 30% 65%, class:org.pulseaudio.pavucontrol

windowrule = float, class:blueman-manager
windowrule = size 35% 55%, class:blueman-manager

windowrule = float, class:anki, title:Options.*
windowrule = stayfocused, class:anki, title:Options.*

windowrule = float, class:showmethekey-gtk
windowrule = persistentsize, class:showmethekey-gtk
windowrule = move 100%-w-20, class:showmethekey-gtk
windowrule = noinitialfocus, class:showmethekey-gtk
windowrule = pin, class:showmethekey-gtk
# at 1197,996
# size 704,6s5

windowrule = float, class:org.kde.kdeconnect.daemon

windowrule = float, class:org.kde.kalk

# Layer Rules
layerrule = dimaround, launcher # Fuzzel

layerrule = dimaround, logout_dialog
layerrule = blur, logout_dialog
