# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
source = ~/.config/hypr/colors.conf

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# For special workspace
# windowrule = opacity 0.5 override opacity 0.8, onworkspace:s[true] # The opacity looks weird over the dim
# windowrule = bordercolor $color13, onworkspace:s[true]
# windowrule = bordersize 2, onworkspace:s[true]
windowrule = noborder, onworkspace:s[true]

# Don't show border on windows when they're the only one in a workspace
windowrulev2 = noborder, onworkspace:w[1]

windowrulev2 = noborder, class:yazi
windowrule = rounding 5, class:yazi

# windowrulev2 = noborder, title:.*lazygit.*

$floorpPasswordDialog = Password Required.*Floorp
windowrule = float, title:$floorpPasswordDialog
windowrule = stayfocused, title:$floorpPasswordDialog

$volumeControlWindow = Volume Control
windowrule = float, title:$volumeControlWindow
windowrule = size 30% 65%, title:$volumeControlWindow

$bluetoothWindow = Bluetooth Devices
windowrule = float, title:$bluetoothWindow
windowrule = size 35% 55%, title:$bluetoothWindow

layerrule = dimaround, launcher # Fuzzel
