# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
source = ~/.config/hypr/colors.conf

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# For special workspace
# windowrule = opacity 0.5 override opacity 0.8, onworkspace:s[true] # The opacity looks weird over the dim
# windowrule = bordercolor $color13, onworkspace:s[true]
# windowrule = bordersize 2, onworkspace:s[true]
windowrule = noborder, onworkspace:s[true]

# Don't show border on windows when they're the only one in a workspace (and that worspace isn't the special)
windowrulev2 = noborder, onworkspace:w[t1], onworkspace:s[false]

windowrulev2 = noborder, class:yazi
windowrule = rounding 0, class:yazi

# windowrulev2 = noborder, title:.*lazygit.*
