# [[manager.prepend_keymap]]
# on = "!"
# run = 'shell "$SHELL" --block' # TODO: open fish instead of bash
# desc = "Open shell here"

# To be able to delete with dd
[[confirm.prepend_keymap]]
on = ["d"]
run = "close --submit"

# TO copy the path of the file on y
[[manager.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo -n "$path "; done | wl-copy -t text/uri-list',
  "yank",
]

[[manager.prepend_keymap]]
on = "<esc>"
run = "escape --all"

#################### bookmakrs ####################

# [[manager.prepend_keymap]]
# on = ["m"]
# run = "plugin bookmarks save"
# desc = "Save current position as a bookmark"
#
# [[manager.prepend_keymap]]
# on = ["'"]
# run = "plugin bookmarks jump"
# desc = "Jump to a bookmark"
#
# [[manager.prepend_keymap]]
# on = ["b", "d"]
# run = "plugin bookmarks delete"
# desc = "Delete a bookmark"
#
# [[manager.prepend_keymap]]
# on = ["b", "D"]
# run = "plugin bookmarks delete_all"
# desc = "Delete all bookmarks"

#################### tab_switch ####################

[[manager.prepend_keymap]]
on = "L"
run = "tab_switch 1 --relative"

[[manager.prepend_keymap]]
on = "H"
run = "tab_switch -1 --relative"

#################### ouch ####################

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

#################### chmod ####################

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "run lazygit"

#################### restore ####################

[[manager.prepend_keymap]]
on = "u"
run = "plugin restore"
desc = "Restore last deleted files/folders"

#################### kdeconnect-send ####################
#
[[manager.prepend_keymap]]
on = ["<C-s>"]
run = "plugin kdeconnect-send"
desc = "Send selected files via KDE Connect"

#################### mount ####################

[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"

#################### toggle/select ####################

[[manager.prepend_keymap]]
on = "K"
run = ["toggle", "arrow prev"]
desc = "Toggle the current selection state and go up"

[[manager.prepend_keymap]]
on = "J"
run = ["toggle", "arrow next"]
desc = "Toggle the current selection state and go down"

#################### smart-enter ####################

# This seems to prevent yazi as a file picker (e.g.: for floorp) to detect opened files
# [[manager.prepend_keymap]]
# on = "l"
# run = "plugin smart-enter"
# desc = "Enter the child directory, or open the file"

#################### preview ####################

[[manager.prepend_keymap]]
on = ["T", "t"]
run = "plugin toggle-pane min-preview"
desc = "Hide or restore the preview pane"

[[manager.prepend_keymap]]
on = ["T", "T"]
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

#################### relative-motions ####################
#
[[manager.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"

#################### projects.yazi ####################
[[manager.prepend_keymap]]
on = ["q"]
run = "plugin projects quit"
desc = "Save last project and exit the process"

[[manager.prepend_keymap]]
on = ["P", "s"]
run = "plugin projects save"
desc = "Save current project"

[[manager.prepend_keymap]]
on = ["P", "l"]
run = "plugin projects load"
desc = "Load project"

[[manager.prepend_keymap]]
on = ["P", "P"]
run = "plugin projects load_last"
desc = "Load last project"

[[manager.prepend_keymap]]
on = ["P", "d"]
run = "plugin projects delete"
desc = "Delete project"

[[manager.prepend_keymap]]
on = ["P", "D"]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[manager.prepend_keymap]]
on = ["P", "m"]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[manager.prepend_keymap]]
on = ["P", "M"]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

#################### Go To ####################
[[manager.prepend_keymap]]
on = ["g", "h"]
run = "cd ~"
desc = "Go home"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Go to Downloads"

[[manager.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/Sync"
desc = "Go to Sync"

[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Go to .config"

[[manager.prepend_keymap]]
on = ["g", "C"]
run = "cd ~/clones"
desc = "Go to clones"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/dev"
desc = "Go to dev"

[[manager.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Pictures"
desc = "Go to Pictures"
