[mgr]
sort_by = "mtime"
sort_reverse = true
# sort_sensitive = true
sort_dir_first = true
# sort_translit = true
linemode = "rmtime"
show_symlink = true
scrolloff = 10
title_format = "yazi {cwd}"

[preview]
wrap = "no"
tab_size = 2
image_delay = 10
max_width = 2500
max_height = 2500

[opener]
gwenview = [{ run = 'gwenview "%s"', orphan = true, for = "unix" }]
okular = [{ run = 'okular "%s"', orphan = true, for = "unix" }]
inkscape = [{ run = 'inkscape "%s"', orphan = true, for = "unix" }]
vlc = [{ run = 'vlc "%s"', orphan = true, for = "unix" }]
ouch = [
  { run = 'ouch d -y "%s"', desc = "extract here with ouch", for = "unix" },
]
onlyoffice = [
  { run = 'onlyoffice-desktopeditors "%s"  --xdg-desktop-portal=default', orphan = true, for = "unix" },
]
appimage = [
  { run = 'gearlever --integrate -y "%1"', orphan = true, desc = "install appimage", for = "unix" },
]
audacity = [{ run = 'audacity "%s"', orphan = true, for = "unix" }]
gimp = [{ run = 'gimp "%s', orphan = true, for = "unix" }]
installFont = [
  { run = '$HOME/scripts/installFont.fish "%s"', orphan = true, desc = "install font", for = "unix" },
]
darktable = [{ run = 'darktable "%s"', orphan = true, for = "unix" }]
kdenlive-import = [
  { run = 'echo "%s" | tr " " "," | xargs kdenlive -i ', orphan = true, desc = "import into kdenlive", for = "unix" },
]
kdenlive = [{ run = 'kdenlive "%s', orphan = true, for = "unix" }]
default = [{ run = 'xdg-open "%s"', desc = "default" }]
edit = [{ run = "$EDITOR %s", desc = "edit", block = true, for = "unix" }]

[open]
append_rules = [{ url = "*", use = "default" }]
prepend_rules = [
  { mime = "image/svg+xml", use = [
    "gwenview",
    "inkscape",
  ] },
  { mime = "image/*", use = [
    "gwenview",
    "gimp",
    "inkscape",
    "darktable",
  ] },
  { mime = "application/pdf", use = [
    "okular",
    "onlyoffice",
  ] },
  { mime = "video/*", use = [
    "vlc",
    "gwenview",
    "kdenlive-import",
  ] },
  { mime = "audio/*", use = [
    "vlc",
    "audacity",
  ] },
  { url = "*.nef", use = [
    "gwenview",
    "darktable",
  ] },
  { mime = "text/*", use = "edit" },
  { url = "*.AppImage", use = "appimage" },
  { url = "*.kdenlive", use = "kdenlive" },
  # Archive
  { mime = "application/x-tar", use = "extract" },
  { mime = "application/x-gtar", use = "extract" },
  { mime = "application/zip", use = "extract" },
  { mime = "application/x-7z-compressed", use = "extract" },
  { mime = "application/7z-compressed", use = "extract" },
  { mime = "application/gzip", use = "extract" },
  { mime = "application/x-xz", use = "extract" },
  { mime = "application/x-lzma", use = "extract" },
  { mime = "application/lzip", use = "extract" },
  { mime = "application/x-bzip", use = "extract" },
  { mime = "application/x-bzip2", use = "extract" },
  { mime = "application/x-bzip3", use = "extract" },
  { url = "*.lz4", use = "extract" },
  { mime = "application/x-snappy-framed", use = "extract" },
  { mime = "application/zstd", use = "extract" },
  { mime = "application/x-rar-compressed", use = "extract" },
  { mime = "application/x-brotli", use = "extract" },
  # Font
  { mime = "font/*", use = "installFont" },                        # TODO: does this work
  { mime = "application/font*", use = "installFont" },
  { mime = "application/x-font*", use = "installFont" },
  { mime = "application/vnd.ms-fontobject", use = "installFont" },
  { mime = "application/ms-opentype", use = "installFont" },
  # Onlyoffice
  # { mime = "application/pdf", use = "onlyoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = "onlyoffice" },
  { mime = "application/msword", use = "onlyoffice" },
  { mime = "application/vnd.ms-word.document.macroenabled.12", use = "onlyoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.template", use = "onlyoffice" },
  { mime = "application/epub+zip", use = "onlyoffice" },
  { mime = "message/rfc822", use = "onlyoffice" },
  { mime = "application/vnd.oasis.opendocument.text", use = "onlyoffice" },
  { mime = "application/vnd.oasis.opendocument.text-template", use = "onlyoffice" },
  { mime = "application/rtf", use = "onlyoffice" },
  { mime = "application/vnd.sun.xml.writer.template", use = "onlyoffice" },
  { mime = "application/vnd.sun.xml.writer", use = "onlyoffice" },
  { mime = "application/vnd.ms-works", use = "onlyoffice" },
  { mime = "text/csv", use = "onlyoffice" },
  { mime = "application/vnd.oasis.opendocument.spreadsheet", use = "onlyoffice" },
  { mime = "application/vnd.oasis.opendocument.spreadsheet-template", use = "onlyoffice" },
  { mime = "application/vnd.sun.xml.calc", use = "onlyoffice" },
  { mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use = "onlyoffice" },
  { url = "*.docx", use = "onlyoffice" },
  { url = "*.xlsx", use = "onlyoffice" },
]

[plugin]
prepend_preloaders = [
  # ################# gvfs.yazi ##################
  # Do not preload files in mounted locations:
  # Environment variable won't work here.
  # Using absolute path instead.
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },
  # For mounted hard disk/drive
  { url = "/run/media/cristobal/**/*", run = "noop" },
  # ################# mediainfo.yazi ##################
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
  # Allow to preview folder.
  { url = "*/", run = "folder" },
  # ################# ouch.yazi ##################
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
  # ################# gvfs.yazi ##################
  # Do not previewing files in mounted locations.
  # Uncomment the line below to allow previewing text files.
  # { mime = "{text/*,application/x-subrip}", run = "code" },
  # Using absolute path.
  { url = "/run/user/1000/gvfs/**/*", run = "noop" },
  # For mounted hard disk/drive.
  { url = "/run/media/cristobal/**/*", run = "noop" },
  # ################# mediainfo.yazi ##################
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]
append_spotters = [{ url = "*", run = "file-extra-metadata" }]
prepend_fetchers = [
  # { id = "git", url = "", run = "git" },
  # { id = "git", url = "*/", run = "git" },
]

[tasks]
# image_alloc = 1073741824  # = 1024*1024*1024 = 1024MB
