#!/bin/sh
# From https://wiki.archlinux.org/title/NetworkManager#Automatically_set_the_timezone
case "$2" in
    up)
        timedatectl set-timezone "$(curl --fail https://ipapi.co/timezone)"
    ;;
esac
