# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
source = ~/.config/hypr/core/common.conf

# Ignore maximize requests from apps. You'll probably like this.
# NOTE: it is commented out to see if it fixes a problem where sometimes a video playing in fullscreen with fast strem player in floorp goes out of fullscreen on its own
# windowrule {
#   name = ignore-maximize-requests
#   match:class = .*
#   suppress_event = maximize
# }

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-dragging-issues
  match:class = negate:audacity
  # match:title = ^$
  match:xwayland = true
  match:float = true
  match:pin = false
  match:fullscreen = false
  no_focus = on
}

windowrule {
  name = anki
  match:class = anki
  match:title = Options.*
  float = on
  center = on
  stay_focused = on
}

windowrule {
  name = blueman-manager
  match:class = blueman-manager
  float = on
  center = on
  size = (monitor_w*0.35) (monitor_h*0.55)
}

windowrule {
  name = bluetui
  match:class = bluetui
  float = on
  center = on
  size = (monitor_w*0.4) (monitor_h*0.3)
}

windowrule {
  name = clipse
  match:class = clipse
  float = on
  size = (monitor_w*0.25) (monitor_h*0.5)
  center = on
  border_size = 1
}

$passwordDialog = Password Required - Zen Browser
windowrule {
  name = zen-password-dialog
  match:class = zen
  match:title = $passwordDialog
  float = on
  center = on
  dim_around = on
  border_size = 1
}

windowrule {
  name = zen-library
  match:class = zen
  match:title = Library
  float = on
  center = on
}

windowrule {
  name = impala
  match:class = impala
  float = on
  center = on
  size = (monitor_w*0.4) (monitor_h*0.5)
}

windowrule {
  name = itunes
  match:class = itunes.exe
  float = on
  center = on
}

windowrule {
  name = kalk
  match:class = org.kde.kalk
  float = on
  center = on
  size = (monitor_w*0.26) (monitor_h*0.6)
}

windowrule {
  name = kcolorchooser
  match:class = org.kde.kcolorchooser
  float = on
  center = on
  border_size = 1
}

windowrule {
  name = kdeconnect
  match:class = org.kde.kdeconnect.daemon
  float = on
  center = on
}

windowrule {
  name = khal
  match:class = khal
  float = on
  center = on
  size = (monitor_w*0.35) (monitor_h*0.55)
  border_size = $bordersize
}

windowrule {
  name = nvim-everywhere
  match:class = nvim-everywhere
  float = on
  center = on
  size = (monitor_w*0.45) (monitor_h*0.3)
  # dim_around = on
}
windowrule {
  name = pavucontrol
  match:class = org.pulseaudio.pavucontrol
  float = on
  center = on
  size = (monitor_w*0.3) (monitor_h*0.65)
}

windowrule {
  name = showmetheykey
  match:class = showmethekey-gtk
  float = on
  persistent_size = on
  no_initial_focus = on
  pin = on
  no_follow_mouse = on
  no_blur = on
  move = (monitor_w-window_w-20) (monitor_h-window_h-20)
  size = (monitor_w*0.3) (monitor_h*0.05)
}

windowrule {
  name = termpicker
  match:class = termpicker
  float = on
  center = on
  size = (monitor_w*0.28) (monitor_h*0.26)
}

windowrule {
  name = tray-tui
  match:class = tray-tui
  float = on
  center = on
  size = (monitor_w*0.6) (monitor_h*0.5)
  border_size = $bordersize
}

windowrule {
  name = dragon-drop
  match:class = dragon-drop
  group = barred
}

windowrule {
  name = gnuplot
  match:class = gnuplot_qt
  float = on
}

windowrule {
  name = zen-browser
  match:class = zen
  opacity = 1 1
}

windowrule {
  name = statgraphics
  match:class = sgwin.exe
  match:float = true
  no_blur = on
}

layerrule {
  name = fuzzel
  match:namespace = launcher
  dim_around = on
}

layerrule {
  name = wlogout
  match:namespace = logout_dialog
  dim_around = on
  blur = on
}
