[[themes]]
name = "carbonfox"
[themes.palette]
background = "#161616"
foreground = "#f2f4f8"
black = "#282828"
red = "#ee5396"
green = "#25be6a"
yellow = "#3ddbd9"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"
bright_black = "#484848"
bright_red = "#f16da6"
bright_green = "#46c880"
bright_yellow = "#2dc7c4"
bright_blue = "#8cb6ff"
bright_magenta = "#c8a5ff"
bright_cyan = "#52bdff"
bright_white = "#e4e4e5"
